version: '3.8'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8082:80"
    depends_on:
      - db
      
  app:
    container_name: nodejs_app_v2
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - db  
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: authism_birge
    # volumes:
    #   - ./server/uploads:/uploads

volumes:
  db_data:  